#!/usr/bin/env python
# coding: utf-8

# In[1]:


'''Customer lifetime value (CLTV) is the estimated total amount a customer will spend on a business throughout their
relationship with that business. It takes into account the revenue generated by the customer as well as the costs
associated with acquiring and serving that customer. By analyzing the relationship between customer acquisition costs 
and revenue generated, we can determine which channels are the most cost-effective for acquiring and retaining high-value 
customers.

The given data includes information about the customer’s channel, cost of acquisition, conversion rate, 
and revenue generated. The Objective is to analyze the CLTV of customers across different channels and identify the most 
profitable channels for the business.'''


# # Importing the necessary Python Library

# In[2]:


import pandas as pd
import plotly.graph_objs as go
import plotly.express as px
import plotly.io as pio
pio.templates.default = "plotly_white"


# In[7]:


data = pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\MY_Projects_Data_Analytics\CLTV aman kharwal\acquisition_data\customer_acquisition_data.csv")
print(data.head())


# # Plotting a Histogram to understand the cost distribution

# In[8]:


fig = px.histogram(data, 
                   x="cost", 
                   nbins=10, 
                   title='Distribution of Acquisition Cost')
fig.show()


# In[5]:


#Observation ->> There are almost 606 customers whose customer acquisition cost is between 5 to 9.9.


# In[18]:


# data.describe()
a=data.shape
print(a)
b= data.describe() #this command Gives us the statistical Summary of all numeric columns of the data set
print(b)


# #  Plotting a Histogram to understand the Revenue distribution

# In[19]:


fig = px.histogram(data, 
                   x="revenue", 
                   nbins=20, 
                   title='Distribution of Revenue')
fig.show()


# In[20]:


#grouping of different channels used by companny based on the cost to use that 
cost_by_channel = data.groupby('channel')['cost'].mean().reset_index()
print(cost_by_channel)

# Plotting a Bar Graph for better analysis
fig = px.bar(cost_by_channel, 
             x='channel', 
             y='cost', 
             title='Customer Acquisition Cost by Channel')
fig.show()


# In[21]:


cost_by_channel


# In[22]:


# grouping of the channels based on the Conversion rate
conversion_by_channel = data.groupby('channel')['conversion_rate'].mean().reset_index()
print(conversion_by_channel)

fig = px.bar(conversion_by_channel, x='channel', 
             y='conversion_rate', 
             title='Conversion Rate by Channel')
fig.show()


# In[23]:


# Indiviaul Channel Contribution towards whole revenue
revenue_by_channel = data.groupby('channel')['revenue'].sum().reset_index()
print(revenue_by_channel)
fig = px.pie(revenue_by_channel, 
             values='revenue', 
             names='channel', 
             title='Total Revenue by Channel', 
             hole=0.5, color_discrete_sequence=px.colors.qualitative.Pastel)

fig.show()


# In[24]:


data['roi'] = data['revenue'] / data['cost']
roi_by_channel = data.groupby('channel')['roi'].mean().reset_index()
print(roi_by_channel)

fig = px.bar(roi_by_channel, 
             x='channel', 
             y='roi', title='Return on Investment (ROI) by Channel')
fig.show()


# In[25]:


data['cltv'] = (data['revenue'] - data['cost']) * data['conversion_rate'] / data['cost']

channel_cltv = data.groupby('channel')['cltv'].mean().reset_index()
print(channel_cltv)

fig = px.bar(channel_cltv, x='channel', y='cltv', color='channel',
             title='Customer Lifetime Value by Channel')

fig.update_xaxes(title='Channel')
fig.update_yaxes(title='CLTV')

fig.show()


# In[26]:


subset = data.loc[data['channel'].isin(['social media', 'referral'])]

fig = px.box(subset, x='channel', y='cltv', title='CLTV Distribution by Channel')

fig.update_xaxes(title='Channel')
fig.update_yaxes(title='CLTV')
fig.update_layout(legend_title='Channel')

fig.show()


# In[ ]:





# In[ ]:




